FileVersion = 1
Projects = {Dimtoo = {Path = "."}, Pile = {Path = "../../Pile"}, Pile_OpenGL = {Path = "../../Implementations/Graphics_OpenGL"}, Pile_SDL2 = {Path = "../../Implementations/System_SDL"}, Pile_SoLoud = {Path = "../../Implementations/Audio_SoLoud"}}
Locked = ["Pile_OpenGL", "Pile_SDL2", "Pile_SoLoud"]

[Workspace]
StartupProject = "Dimtoo"
