FileVersion = 1
Dependencies = {corlib = "*", "Atma.Json" = "*"}

[Project]
Name = "Pile"

[Configs.Release.Win64]
PostBuildCmds = ["Execute(\"$(TargetPath PileGame).exe -packager\")"]

[Configs.Release.Linux64]
PostBuildCmds = ["Execute(\"$(TargetPath PileGame) -packager\")"]
